// THIS FILE IS GENERATED BY TOOL, PLEASE DO NOT EDIT!

import Foundation

struct R {

    enum string : String {
        /// Growth of GDP
        case data_dataset1_name
        /// Growth of population
        case data_dataset2_name
        /// Ok
        case game_change_confirm_btn
        /// Pass phone to %1$@
        case game_change_player_text
        /// Confrim
        case game_delegate_confirm_btn
        /// Delegate workers
        case game_delegate_workers_title
        /// End turn
        case game_end_turn_btn
        /// Select %1$@
        case game_select_country
        /// Andorra
        case game_select_country_country_AD
        /// Albania
        case game_select_country_country_AL
        /// Armenia
        case game_select_country_country_AM
        /// Austria
        case game_select_country_country_AU
        /// Azerbaijan
        case game_select_country_country_AZ
        /// Bosnia and Herzegovina
        case game_select_country_country_BA
        /// Belgium
        case game_select_country_country_BE
        /// Bulgaria
        case game_select_country_country_BG
        /// Belarus
        case game_select_country_country_BY
        /// Switzerland
        case game_select_country_country_CH
        /// Czech Republic
        case game_select_country_country_CY
        /// Germany
        case game_select_country_country_DE
        /// Denmark
        case game_select_country_country_DK
        /// Estonia
        case game_select_country_country_EE
        /// Greece
        case game_select_country_country_EL
        /// Spain
        case game_select_country_country_ES
        /// Finland
        case game_select_country_country_FI
        /// France
        case game_select_country_country_FR
        /// Georgia
        case game_select_country_country_GE
        /// Croatia
        case game_select_country_country_HR
        /// Hungary
        case game_select_country_country_HU
        /// Ireland
        case game_select_country_country_IE
        /// Iceland
        case game_select_country_country_IS
        /// Italy
        case game_select_country_country_IT
        /// Liechtenstein
        case game_select_country_country_LI
        /// Lithuania
        case game_select_country_country_LT
        /// Luxembourg
        case game_select_country_country_LU
        /// Latvia
        case game_select_country_country_LV
        /// Monaco
        case game_select_country_country_MC
        /// Moldova
        case game_select_country_country_MD
        /// RepublicOfMacedonia
        case game_select_country_country_MK
        /// Malta
        case game_select_country_country_MT
        /// Netherlands
        case game_select_country_country_NL
        /// Norway
        case game_select_country_country_NO
        /// Poland
        case game_select_country_country_PL
        /// Portugal
        case game_select_country_country_PT
        /// Romania
        case game_select_country_country_RO
        /// Serbia
        case game_select_country_country_RS
        /// Russia
        case game_select_country_country_RU
        /// Sweden
        case game_select_country_country_SE
        /// Slovenia
        case game_select_country_country_SI
        /// Slovakia
        case game_select_country_country_SK
        /// San Marino
        case game_select_country_country_SM
        /// Turkey
        case game_select_country_country_TR
        /// Ukraine
        case game_select_country_country_UA
        /// United Kingdom
        case game_select_country_country_UK
        /// Wrong country!!
        case game_select_country_invalid
        /// Ok
        case game_tutorial_close_btn
        /// Zasady gry:
        ///  ▰4 graczy;
        ///  ▰Każdy gracz posiada 100 pracowników;
        ///  ▰6 Rynków(Krajów) do zagospodarowania;
        ///  ▰Każdy z graczy w jednej turze może delegować maksymalnie 20 pracowników;
        ///  ▰ Wygrywa gracz który zajął największą liczbę państw;
        ///  ▰Państwo zajmuje gracz z największą liczbą pracowników na danym terytorium po wszystkich turach.
        ///  ▰Gracze rywalizują pomiędzy sobą w turowym muliplayerze na jedno urządzenie;
        ///  ▰Każdy gracz po delegowaniu pracowników na dane pole otrzymuje do poglądu trzy statystki w formie histogramów oraz nazwę statystyki;
        ///  ▰Następnie zadaniem gracza jest poprawnie określenie lat dla każdego z trzech prostopadłościanów histogramu, czyli danej statystyki i danego państwa;
        ///  ▰Gra toczy się, aż ostatni z graczy wyśle wszystkich swoich pracowników. 
        ///  ▰Dodatkowy element służący do nauki na początku każdej tury: 
        ///  – wskazanie przez każdego kolejnego gracza rozpoczynającego turę właściwego państwa. 
        ///  Ile punktów dostaje gracz:
        ///  ▰Za 3 poprawne odpowiedzi - liczba pracowników razy 2
        ///  ▰Za 1 poprawną odpowiedź - liczba pracowników taka ja wydelegowana na początku
        ///  ▰Za 0 poprawnych odpowiedzi – liczba pracowników zmniejszona o połowę.
        /// 
        case game_tutorial_text
        /// test it's ok
        case test
        /// integer %d, string %@
        case test_parameters1
        /// string %2$@, integer %1$d
        case test_parameters2
    }

    enum plurals : String {
        case game_delegate_workers_count
        case test_plurals

        subscript(quantity: Int) -> String {
            return String.localizedStringWithFormat(NSLocalizedString(self.rawValue, comment: ""), quantity)
        }
    }

}

